name: Tests
on: pull_request

jobs:
  checks:
    name: Analyzer and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Getting packages
        run: flutter pub get
      - name: analyzis
        run: flutter analyze .
      - name: tests
        run: flutter test